[metadata]
name = tpllg
version = attr: tpllg.__version__
description = Acquisition à la Sysam SP5 et exploitation des mesures en TP de physique (CPGE)
long_description = file: README.md
long_description_content_type = text/markdown
author = Antonin Marchand
url = https://github.com/antnardo/tpllg
license = CC-BY-NC-SA-4.0
classifiers =
    Programming Language :: Python :: 3
    Intended Audience :: Education
    Topic :: Scientific/Engineering :: Physics

[options]
packages = tpllg
python_requires = >=3.7
install_requires =
    numpy
    scipy
    matplotlib
